version: "3.8"

services:
  proxy:
    image: classroom-conversation/nginx:latest
    build:
      context: ./nginx
      target: development
    ports:
      - 8080:8080

  backend:
    image: classroom-conversation/backend:latest
    build:
      context: ./backend
      target: development
    volumes:
      - ./backend/classroomconversation/classroomconversation:/app/classroomconversation:ro
      - ./backend/classroomconversation/conversation:/app/conversation:ro
      - ./backend/classroomconversation/manage.py:/app/manage.py:ro
      - ./backend/classroomconversation/templates:/app/templates
      - ./backend/classroomconversation/locale:/app/locale
    ports:
      - 5678:5678
    
  frontend:
    image: classroom-conversation/frontend:latest
    build:
      context: ./frontend
      target: development
    volumes:
      - ./frontend/src:/app/src
    environment:
      - NODE_ENV=development
      - DEBUG=1
    stdin_open: true
